language: php

php:
  - 5.5

before_script:
  - cp config/eventstore.config.php.travis config/eventstore.config.php
  - composer self-update
  - composer update

script:
  - php ./vendor/bin/phpunit -c ./tests/.

